In [1]:
import numpy as np
import pandas as pd

### Creating a DataFrame

We can create DataFrame using arrays, dictionaries, and list.

In [3]:
data = {
    'Name' : ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New york', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
} # This is a dictionary

df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
# Dataframe using List
data_list = [
    ['John', 28, 'New york', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [10]:
df2

       0   1         2      3
0   John  28  New york  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In dictionary we can get the name of columns directly, but when using lists, we will get default 0,1,2,... in both rows and columns.

We can assign columns in the DataFrame using another list.

In [13]:
columns = ['Name', 'Age', 'City', 'Salary']

In [15]:
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New york   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df2['Name'] # Selecting a single column

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [19]:
df2['City']

0    New york
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [21]:
df2[['Name', 'City']] # Selecting multiple columns, we need to create list of lists

    Name      City
0   John  New york
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Creating a new column

In [24]:
df2['Designation'] = ['Doctor', 'Engineer', 'Doctor', 'Engineer']
df2

    Name  Age      City  Salary Designation
0   John   28  New york   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

### Removing a column

In [27]:
df2.drop('Designation')

KeyError: "['Designation'] not found in axis"

We got error because drop checks rows by default, i.e. it didnot find designation in rows

We want python to check columns instead of rows, for that we need to send **'axis=1'** as second parameter in drop. **'axis=0'** is default in drop.

In [ ]:
df2.drop('Designation', axis = 1)

In [ ]:
df2

The column don't get deleted. It just gives the view of the dataframe if the columns isn't there.

In [ ]:
df2.drop('Designation', axis = 1, inplace = True) # to remove from the table

In [ ]:
df2

In [ ]:
df2.drop(['City', 'Salary'], axis = 1) # to remove multiple columns

In [ ]:
df2.drop(0, axis = 0) # to remove rows

## Selecting rows

In [40]:
df2

    Name  Age      City  Salary Designation
0   John   28  New york   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [44]:
df2.loc[0] # loc is location and it is for rows

Name               John
Age                  28
City           New york
Salary            65000
Designation      Doctor
Name: 0, dtype: object

In [50]:
df2.loc[[0, 1]] # for selecting multiple rows

   Name  Age      City  Salary Designation
0  John   28  New york   65000      Doctor
1  Anna   34     Paris   70000    Engineer

In [54]:
df.iloc[3] # this means index location and it is used when index is different, rn there is 0, 1, 2... but it can be different

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

## Selecting subsets of rows and columns

In [57]:
df2.loc[[0, 1]][['City', 'Salary']]

       City  Salary
0  New york   65000
1     Paris   70000

In [63]:
df2.loc[[2, 3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

## Conditional statement

It means to select based on some conditions

In [78]:
# people whose age is above 30
df2[df2['Age'] > 30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000    Engineer

In [90]:
# people whose age is above 30 and their city must be paris 
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000    Engineer